console.log("Application Started");
console.log("Database Connected");
console.log("User Visited Homepage");
console.log("Product Search: 'wireless headphones'");
console.log("Product Page Viewed: Item #8492");
console.log("Item Added to Cart: Item #8492");
console.log("Checkout Initiated");
console.log("Payment Completed");
console.log("Order Confirmation Email Sent");
console.log("User Logged Out");
